DROP TABLE OrderDetail ;
DROP TABLE [Order] ;
DROP TABLE SupplierEmployee ;
DROP TABLE Track ;
DROP TABLE SalaryHistory ;
DROP TABLE JobHistory ;
DROP TABLE Schedule ;
DROP TABLE Announcement; 
DROP TABLE Accounting ;
DROP TABLE Email ;
DROP TABLE Branch ;
DROP TABLE PhoneNumber ;
DROP TABLE [Address];
DROP TABLE Customer ;
DROP TABLE Employee ;
DROP TABLE Person ;
DROP TABLE InventoryPurchaseDetail ;
DROP TABLE InventoryPurchase ;
DROP TABLE Inventory ;
DROP TABLE Delivery ;
DROP TABLE SalaryGrade ;
DROP TABLE Promotion ;
DROP TABLE Supplier ;
DROP TABLE [Shift] ;
DROP TABLE MembershipLevel ;

DROP TABLE InventoryShown;
DROP TABLE Fax;
DROP TABLE BranchCategory;
DROP TABLE AddressType;
DROP TABLE EmailType;
DROP TABLE TransactionType;
DROP TABLE CostCategory;
DROP TABLE MarriageStatus; 
DROP TABLE ValidStatus;
DROP TABLE CostCategory;
DROP TABLE PreferredContact ;
DROP TABLE PhoneNumberType ;
DROP TABLE JobTitle ;
DROP TABLE PromotionType ;
DROP TABLE SupplierType ;
DROP TABLE ShiftType ;
DROP TABLE Invoice ;
DROP TABLE PaymentMethod ;
DROP TABLE DeliveryType ;
DROP TABLE DeliveryStatus ;
DROP TABLE Color ;
DROP TABLE Size ;
DROP TABLE InventoryType ;
DROP TABLE DeliverySupplier ;
DROP TABLE Gender ;
DROP TABLE SignOffStatus ;
DROP TABLE ConfirmStatus ;
DROP TABLE SoleMaterial ;
DROP TABLE UpperMaterial ;